# path to gzipped ref genome
genome_fa_gz: /home/ec2-user/GRCh37.p13.genome.fa.gz

# path to gzipped GENCODE annotation
annotation_gtf_gz: /home/ec2-user/gencode.v19.annotation.gtf.gz

# directory where you want to install database
db_dir: /home/ec2-user/resource/riboduct_db

# if you use SGE cluster, set the maximum number of jobs
# sge_jobs: 100

#readFilesCommand: "cat" # for uncompressed FASTQ
#readFilesCommand: "gunzip -c" # for gzipped FASTQ
readFilesCommand: "bunzip2 -c" # for bzip2-compressed FASTQ

fastq:
  sample_A:
    - example/run1/sample_A.R1.fastq.bz2
    - example/run1/sample_A.R2.fastq.bz2
  sample_B: # multiple runs from the same library
    - [example/run1/sample_B.R1.fastq.bz2, example/run2/sample_B.R1.fastq.bz2]
    - [example/run1/sample_B.R2.fastq.bz2, example/run2/sample_B.R2.fastq.bz2]
