# directory where you want to install database
db_dir: /path/to/db

# set the same value to $CONDA_PREFIX
env_dir: /path/to/env

fastq:
  sample_A:
    - fastq/run1/sample_A.R1.fastq
    - fastq/run1/sample_A.R2.fastq
  sample_B:
    - [fastq/run1/sample_B.R1.fastq, fastq/run2/sample_B.R1.fastq]
    - [fastq/run1/sample_B.R2.fastq, fastq/run2/sample_B.R2.fastq]
