# directory where you want to install database
db_dir: /path/to/db

fastq:
  sample_A:
    - example/run1/sample_A.R1.fastq
    - example/run1/sample_A.R2.fastq
  sample_B:
    - [example/run1/sample_B.R1.fastq, example/run2/sample_B.R1.fastq]
    - [example/run1/sample_B.R2.fastq, example/run2/sample_B.R2.fastq]
