name: riboduct
channels:
  - r
  - bioconda
dependencies:
  - snakemake=3.13.3
  - star=2.5.3a
  - rna-seqc=1.1.8
  - subread=1.6.0
  - samtools=1.6
  - picard=2.15.0
  - r=3.3.1
  - r-dplyr=0.7.4
  - r-data.table=1.10.4
  - r-readr=0.2.2
