name: riboduct
channels:
  - r
  - bioconda
dependencies:
  - snakemake
  - star
  - subread
  - samtools
  - picard
  - rna-seqc
  - r
  - r-dplyr
  - r-data.table
  - r-readr
  - java-jdk=7.0.91
  - pandas
